language: node_js
node_js:
  - "stable"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
script:
  - npm run nyc

jobs:
  matrix:
    - name: Run lint
      node_js: "stable"
      script: npm run lint
    - node_js: "7"
      script: npm run test
    - node_js: "6"
      script: npm run test
    - node_js: "4"
      script: npm run test
