language: node_js
node_js:
  - "stable"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
script:
  - npm run test:cov

jobs:
  include:
    - name: Run lint
      node_js: "stable"
      script: npm run lint
    - node_js: "7"
      script: npm run test:no-cov
    - node_js: "6"
      script: npm run test:no-cov
    - node_js: "4"
      script: npm run test:no-cov
